// Generates docs/MCQ_ANSWER_KEY_AUDIT.md: per-course verified/missing counts + a full list of the
// questions still missing an answer key (Option B: documented, not hidden). Run: node scripts/audit-mcqs.mjs
import fs from "node:fs";

const read = (p) => fs.readFileSync(p, "utf8");
const cat = JSON.parse(read("src/data/courses-catalogue.ts").match(/coursesCatalogue[^=]*=\s*(\[[\s\S]*?\]);/)[1]);
const learning = JSON.parse(read("src/data/course-learning.ts").match(/courseLearning[^=]*=\s*(\{[\s\S]*?\});\s*\n\nexport const getCourseLearning/)[1]);
const answersSrc = read("src/data/quiz-answers.ts");
const title = Object.fromEntries(cat.map((c) => [c.slug, c.title]));

const norm = (s) => (s || "").trim().replace(/\s+/g, " ").toLowerCase();
const keys = {};
for (const block of answersSrc.matchAll(/"([a-z0-9-]+)":\s*\[([\s\S]*?)\n\s*\]/g)) {
  const map = new Map();
  for (const m of block[2].matchAll(/prompt:\s*"((?:[^"\\]|\\.)*)"\s*,\s*correct:\s*\[([^\]]*)\]/g))
    map.set(norm(m[1].replace(/\\"/g, '"')), m[2].split(",").filter((x) => x.trim()).map(Number));
  keys[block[1]] = map;
}

const GENERIC = /^(question|multiple\s*choice(\s*#?\d+)?|exercise(\s*-\s*multiple\s*(choice|answer))?|quiz|test)\s*$/i;
const meaningful = (t) => t.trim().length > 0 && !GENERIC.test(t.trim());

let total = 0, verified = 0, missing = 0;
const perCourse = [];
const missingRows = [];

for (const slug of Object.keys(learning)) {
  const km = keys[slug] || new Map();
  let cTotal = 0, cVer = 0, counter = 0, setTitle = "";
  for (const section of learning[slug]) {
    let open = null;
    const flush = () => { if (open) { counter++; open = null; } };
    for (const u of section.units) {
      if (u.q) {
        if (meaningful(u.t) || !open) { flush(); counter++; setTitle = meaningful(u.t) ? u.t : `Exercise ${counter}`; open = { id: `quiz-${counter}`, i: 0 }; }
        const qid = `${open.id}-q${open.i++}`;
        total++; cTotal++;
        if (km.has(norm(u.q.p))) { verified++; cVer++; }
        else {
          missing++;
          missingRows.push({ slug, section: section.title, set: setTitle, qid, q: u.q.p, type: u.q.m ? "multiple-choice" : "single-choice" });
        }
      } else flush();
    }
    flush();
  }
  if (cTotal) perCourse.push({ slug, t: title[slug] || slug, total: cTotal, verified: cVer, missing: cTotal - cVer });
}

const coursesMissing = perCourse.filter((c) => c.missing > 0).length;
let md = `# MCQ Answer Key Audit

Verified answer keys are harvested from the live BoostMySkills course player via the **"Show Answer"**
feature (\`scripts/harvest-answers.mjs\`) and a few are user-verified, then matched to our questions by
exact prompt text (\`scripts/gen-answers.mjs\`). This file is regenerated by \`node scripts/audit-mcqs.mjs\`.

| Metric | Value |
| --- | --- |
| Total MCQ questions (62 scraped courses) | **${total}** |
| **Verified** answer keys (validate locally) | **${verified}** |
| **Missing / unavailable** after inspection | **${missing}** |
| Invalid answer keys | **0** |
| Courses with all keys verified | ${perCourse.length - coursesMissing} / ${perCourse.length} |
| Courses still missing some keys | ${coursesMissing} |

**Method:** "Show Answer" was enabled for these courses, so the correct option(s) are read directly
from the graded problem — not guessed. Where a question's prompt/options could not be matched
(e.g. randomised variants, non-choice inputs, or Show-Answer disabled for that block), it is listed
below as **unavailable** and the player shows the neutral *"answer key … not available locally yet"*
message for it (never the old "graded inside BoostMySkills" text).

## Per-course summary

| # | Course | Slug | Questions | Verified | Missing |
| --- | --- | --- | --- | --- | --- |
`;
perCourse.sort((a, b) => b.missing - a.missing || a.t.localeCompare(b.t));
perCourse.forEach((c, i) => { md += `| ${i + 1} | ${c.t} | ${c.slug} | ${c.total} | ${c.verified} | ${c.missing} |\n`; });

md += `\n## Questions still unavailable after live inspection (${missingRows.length})\n\n`;
if (!missingRows.length) {
  md += `None — every MCQ has a verified answer key.\n`;
} else {
  md += `| Course | Section | Quiz set | Question id | Type | Question |\n| --- | --- | --- | --- | --- | --- |\n`;
  for (const r of missingRows) {
    const q = r.q.replace(/\|/g, "\\|").slice(0, 140);
    md += `| ${r.slug} | ${r.section} | ${r.set} | ${r.qid} | ${r.type} | ${q} |\n`;
  }
}

fs.writeFileSync("docs/MCQ_ANSWER_KEY_AUDIT.md", md);
console.log(`Wrote docs/MCQ_ANSWER_KEY_AUDIT.md — total ${total}, verified ${verified}, missing ${missing}, courses missing ${coursesMissing}.`);
